name: Backup on Merge

on:
  pull_request:
    types:
      - closed

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Check PR merge
      if: github.event.pull_request.merged == true
      run: echo "PR was merged."

    - name: Set Git config
      run: |
        git config --global user.email ${{ secrets.GIT_USER_EMAIL }}
        git config --global user.name ${{ secrets.GIT_USER_NAME }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Pull from Feature/Dev to backup
      run: git pull --no-rebase --allow-unrelated-histories origin Feature/Dev:backup

